server:
  port: 8090
  servlet:
    context-path: /server

#redis
redis:
  host: 127.0.0.1
  port: 6379
#  连接超时时间
  timeout: 10
  poolMaxTotal: 1000
#  最大空闲
  poolMaxIdle: 500
#  最大等待时间
  poolMaxWait: 500
  password: zhanghang